title: Home
author: Thilak
email: thilak746@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I have just began to learn about GitHub pages using Jekyll, so I'm editing the config.yml file here.

# social links
twitter_username: ka1iht # DO NOT include the @ character, or else the build will fail!
github_username:  ka1iht # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
